{
 "title": "Brocade: Switch Overview (Realtime)",
 "tags": [
  "Brocade",
  "Realtime"
 ],
 "time": { "from": "2023-07-27T07:41:16.319Z", "to": "2023-07-27T08:48:46.331Z" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "Fabric", "query": "brocade.fos.perf.switches.*" },
   {
    "name": "Switch",
    "query": "brocade.fos.perf.switches.$Fabric.*"
   }
  ]
 },
 "panels": [
  {
   "title": "CPU utilization $Fabric / $Switch",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 16, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "target": "aliasByNode(brocade.fos.perf.switches.$Fabric.$Switch.cpu-usage, 5)"
    }
   ]
  },
  {
   "title": "Current CPU utilization $Fabric / $Switch",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "aliasByNode(brocade.fos.perf.switches.$Fabric.$Switch.cpu-usage, 5)"
    }
   ]
  },
  {
   "title": "Memory utilization $Fabric / $Switch",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 16, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "target": "aliasByNode(brocade.fos.perf.switches.$Fabric.$Switch.memory-usage, 5)"
    }
   ]
  },
  {
   "title": "Current Memory utilization $Fabric / $Switch",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "aliasByNode(brocade.fos.perf.switches.$Fabric.$Switch.memory-usage, 5)"
    }
   ]
  },
  {
   "title": "Flash utilization $Fabric / $Switch",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 16, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "target": "aliasByNode(brocade.fos.perf.switches.$Fabric.$Switch.flash-usage, 5)"
    }
   ]
  },
  {
   "title": "Current flash utilization $Fabric / $Switch",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "aliasByNode(brocade.fos.perf.switches.$Fabric.$Switch.flash-usage, 5)"
    }
   ]
  }
 ]
}