{
 "title": "Brocade: ISL Overview (Realtime)",
 "tags": [
  "Brocade",
  "Realtime"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "Fabric", "query": "brocade.fos.stats.ports.*" },
   {
    "name": "Switch",
    "query": "brocade.fos.stats.ports.$Fabric.*"
   },
   {
    "name": "errorcounter",
    "query": "Physical coding sublayer errors : pcs, Encoding OUT errors : enc_out, CRC errors : crc-errors, Invalid ordered set : inv_os, Link failures : link-failures, Link reset IN : lr_in, Link reset OUT : lr_out, Loss of sync : loss-of-sync, Loss of signal : loss-of-signal, C3 discards : class-3-discards, C3 RXTO discards : c3_rxto, C3 TXTO discards : c3_txto"
   }
  ]
 },
 "panels": [
  {
   "title": "Performance: Long distance ISLs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "RX throughput of long distance ISLs for $Fabric / $Switch",
   "type": "graph",
   "gridPos": { "h": 9, "w": 9, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "target": "sortByMaxima(aliasByNode(scaleToSeconds(nonNegativeDerivative(brocade.fos.perf.ports.$Fabric.$Switch.LS_PORT.*.*.in-octets), 1), 5, 7, 8))"
    }
   ]
  },
  {
   "title": "RX throughput of long distance ISLs for $Fabric / $Switch",
   "type": "stat",
   "gridPos": { "h": 9, "w": 3, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "averageSeries(scaleToSeconds(nonNegativeDerivative(brocade.fos.perf.ports.$Fabric.$Switch.LS_PORT.*.*.in-octets), 1))"
    }
   ]
  },
  {
   "title": "TX throughput of long distance ISLs for $Fabric / $Switch",
   "type": "graph",
   "gridPos": { "h": 9, "w": 9, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "target": "sortByMaxima(aliasByNode(scaleToSeconds(nonNegativeDerivative(brocade.fos.perf.ports.$Fabric.$Switch.LS_PORT.*.*.out-octets), 1), 5, 7, 8))"
    }
   ]
  },
  {
   "title": "TX throughput of long distance ISLs for $Fabric / $Switch",
   "type": "stat",
   "gridPos": { "h": 9, "w": 3, "x": 21, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "averageSeries(scaleToSeconds(nonNegativeDerivative(brocade.fos.perf.ports.$Fabric.$Switch.LS_PORT.*.*.out-octets), 1))"
    }
   ]
  },
  {
   "title": "Errors: Long distance ISLs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "panels": [
    {
     "title": "$errorcounter for $Fabric / $Switch",
     "type": "table",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 11 },
     "repeat": "errorcounter",
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "target": "aliasByNode(highestAverage(nonNegativeDerivative(brocade.fos.stats.ports.$Fabric.$Switch.LS_PORT.*.*.$errorcounter), 20), 5, 7, 8)"
      }
     ]
    }
   ]
  },
  {
   "title": "Performance: Standard distance ISLs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 }
  },
  {
   "title": "RX throughput of ISLs for $Fabric / $Switch",
   "type": "graph",
   "gridPos": { "h": 9, "w": 9, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "target": "sortByMaxima(aliasByNode(scaleToSeconds(nonNegativeDerivative(brocade.fos.perf.ports.$Fabric.$Switch.E_PORT.*.*.in-octets), 1), 5, 7, 8))"
    }
   ]
  },
  {
   "title": "RX throughput of ISLs for $Fabric / $Switch",
   "type": "stat",
   "gridPos": { "h": 9, "w": 3, "x": 9, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "averageSeries(scaleToSeconds(nonNegativeDerivative(brocade.fos.perf.ports.$Fabric.$Switch.E_PORT.*.*.in-octets), 1))"
    }
   ]
  },
  {
   "title": "TX throughput of ISLs for $Fabric / $Switch",
   "type": "graph",
   "gridPos": { "h": 9, "w": 9, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "target": "sortByMaxima(aliasByNode(scaleToSeconds(nonNegativeDerivative(brocade.fos.perf.ports.$Fabric.$Switch.E_PORT.*.*.out-octets), 1), 5, 7, 8))"
    }
   ]
  },
  {
   "title": "TX throughput of ISLs for $Fabric / $Switch",
   "type": "stat",
   "gridPos": { "h": 9, "w": 3, "x": 21, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "averageSeries(scaleToSeconds(nonNegativeDerivative(brocade.fos.perf.ports.$Fabric.$Switch.E_PORT.*.*.out-octets), 1))"
    }
   ]
  },
  {
   "title": "Errors: Standard distance ISLs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "collapsed": true,
   "panels": [
    {
     "title": "$errorcounter for $Fabric / $Switch",
     "type": "table",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 22 },
     "repeat": "errorcounter",
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "target": "aliasByNode(highestAverage(nonNegativeDerivative(brocade.fos.stats.ports.$Fabric.$Switch.E_PORT.*.*.$errorcounter), 20), 5, 7, 8)"
      }
     ]
    }
   ]
  }
 ]
}