{
 "title": "Brocade: Port Status (Realtime)",
 "tags": [
  "Brocade",
  "Realtime"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   { "name": "Fabric", "query": "brocade.fos.stats.ports.*" },
   {
    "name": "Switch",
    "query": "brocade.fos.stats.ports.$Fabric.*"
   },
   {
    "name": "Porttype",
    "query": "brocade.fos.stats.ports.$Fabric.$Switch.*"
   },
   {
    "name": "Slot",
    "query": "brocade.fos.stats.ports.$Fabric.$Switch.$Porttype.*"
   },
   {
    "name": "Port",
    "query": "brocade.fos.stats.ports.$Fabric.$Switch.$Porttype.$Slot.*"
   },
   {
    "name": "errorcounter",
    "query": "Physical coding sublayer errors : pcs, Encoding OUT errors : enc_out, CRC errors : crc-errors, Invalid ordered set : inv_os, Link failures : link-failures, Link reset IN : lr_in, Link reset OUT : lr_out, Loss of sync : loss-of-sync, Loss of signal : loss-of-signal, C3 discards : class-3-discards, C3 RXTO discards : c3_rxto, C3 TXTO discards : c3_txto"
   }
  ]
 },
 "panels": [
  {
   "title": "Performance Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Aggregated throughput for all selected ports ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 20, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "target": "alias(sumSeries(scaleToSeconds(nonNegativeDerivative(brocade.fos.perf.ports.$Fabric.$Switch.$Porttype.$Slot.$Port.in-octets), 1)), 'Aggregated RX Throughput')"
    },
    {
     "target": "alias(sumSeries(scaleToSeconds(nonNegativeDerivative(brocade.fos.perf.ports.$Fabric.$Switch.$Porttype.$Slot.$Port.out-octets), 1)), 'Aggregated TX Throughput')"
    }
   ]
  },
  {
   "title": "Aggregated RX/TX Ratio all selected ports ",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "target": "alias(sumSeries(scaleToSeconds(nonNegativeDerivative(brocade.fos.perf.ports.$Fabric.$Switch.$Porttype.$Slot.$Port.in-octets), 1)), 'Aggregated RX Throughput')"
    },
    {
     "target": "alias(sumSeries(scaleToSeconds(nonNegativeDerivative(brocade.fos.perf.ports.$Fabric.$Switch.$Porttype.$Slot.$Port.out-octets), 1)), 'Aggregated TX Throughput')"
    }
   ]
  },
  {
   "title": "Port RX throughput for all selected ports ",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "target": "aliasByNode(scaleToSeconds(nonNegativeDerivative(brocade.fos.perf.ports.$Fabric.$Switch.$Porttype.$Slot.$Port.in-octets), 1), 5, 7, 8)"
    }
   ]
  },
  {
   "title": "Port TX throughput for all selected ports ",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "target": "aliasByNode(scaleToSeconds(nonNegativeDerivative(brocade.fos.perf.ports.$Fabric.$Switch.$Porttype.$Slot.$Port.out-octets), 1), 5, 7, 8)"
    }
   ]
  },
  {
   "title": "Error Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "$errorcounter",
     "type": "table",
     "gridPos": { "h": 9, "w": 6, "x": 0, "y": 20 },
     "repeat": "errorcounter",
     "targets": [
      {
       "target": "aliasByNode(nonNegativeDerivative(brocade.fos.stats.ports.$Fabric.$Switch.$Porttype.$Slot.$Port.$errorcounter), 5, 7, 8)"
      }
     ]
    }
   ]
  },
  {
   "title": "Error Details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "$errorcounter",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 21 },
     "repeat": "errorcounter",
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "target": "aliasByNode(scaleToSeconds(nonNegativeDerivative(brocade.fos.stats.ports.$Fabric.$Switch.$Porttype.$Slot.$Port.$errorcounter), 1), 5, 7, 8)"
      }
     ]
    }
   ]
  },
  {
   "title": "SFP Details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "targets": [
    {}
   ]
  },
  {
   "title": "SPF RX power in dBm",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "dBm" } },
   "targets": [
    {
     "target": "aliasByNode(brocade.fos.stats.ports.$Fabric.$Switch.$Porttype.$Slot.$Port.rx-power-dbm, 5, 7, 8)"
    }
   ]
  },
  {
   "title": "SPF TX power in dBm",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "dBm" } },
   "targets": [
    {
     "target": "aliasByNode(brocade.fos.stats.ports.$Fabric.$Switch.$Porttype.$Slot.$Port.tx-power-dbm, 5, 7, 8)"
    }
   ]
  },
  {
   "title": "SPF RX power in milliwatt",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "mwatt" } },
   "targets": [
    {
     "target": "aliasByNode(brocade.fos.stats.ports.$Fabric.$Switch.$Porttype.$Slot.$Port.rx-power, 5, 7, 8)"
    }
   ]
  },
  {
   "title": "SPF TX power in milliwatt",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "mwatt" } },
   "targets": [
    {
     "target": "aliasByNode(brocade.fos.stats.ports.$Fabric.$Switch.$Porttype.$Slot.$Port.tx-power, 5, 7, 8)"
    }
   ]
  }
 ]
}