{
 "title": "Brocade: Port Status (Realtime)",
 "tags": [
  "Brocade",
  "Realtime"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "Fabric", "query": "brocade.fos.stats.ports.*" },
   {
    "name": "Switch",
    "query": "brocade.fos.stats.ports.$Fabric.*"
   },
   {
    "name": "Porttype",
    "query": "brocade.fos.stats.ports.$Fabric.$Switch.*"
   },
   {
    "name": "Slot",
    "query": "brocade.fos.stats.ports.$Fabric.$Switch.$Porttype.*"
   },
   {
    "name": "Port",
    "query": "brocade.fos.stats.ports.$Fabric.$Switch.$Porttype.$Slot.*"
   }
  ]
 },
 "panels": [
  { "title": "Performance Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Aggregated throughput for all selected ports ",
   "type": "graph",
   "gridPos": { "h": 8, "w": 20, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "target": "alias(sumSeries(scaleToSeconds(nonNegativeDerivative(brocade.fos.perf.ports.$Fabric.$Switch.$Porttype.$Slot.$Port.in-octets), 1)), 'Aggregated RX Throughput')"
    },
    {
     "target": "alias(sumSeries(scaleToSeconds(nonNegativeDerivative(brocade.fos.perf.ports.$Fabric.$Switch.$Porttype.$Slot.$Port.out-octets), 1)), 'Aggregated TX Throughput')"
    }
   ]
  },
  {
   "title": "Aggregated RX/TX Ratio all selected ports ",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 1 },
   "format": "Bps",
   "valueName": "avg",
   "targets": [
    {
     "target": "alias(sumSeries(scaleToSeconds(nonNegativeDerivative(brocade.fos.perf.ports.$Fabric.$Switch.$Porttype.$Slot.$Port.in-octets), 1)), 'Aggregated RX Throughput')"
    },
    {
     "target": "alias(sumSeries(scaleToSeconds(nonNegativeDerivative(brocade.fos.perf.ports.$Fabric.$Switch.$Porttype.$Slot.$Port.out-octets), 1)), 'Aggregated TX Throughput')"
    }
   ]
  },
  {
   "title": "Port RX throughput for all selected ports ",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "target": "aliasByNode(scaleToSeconds(nonNegativeDerivative(brocade.fos.perf.ports.$Fabric.$Switch.$Porttype.$Slot.$Port.in-octets), 1), 5, 7, 8)"
    }
   ]
  },
  {
   "title": "Port TX throughput for all selected ports ",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "target": "aliasByNode(scaleToSeconds(nonNegativeDerivative(brocade.fos.perf.ports.$Fabric.$Switch.$Porttype.$Slot.$Port.out-octets), 1), 5, 7, 8)"
    }
   ]
  },
  {
   "title": "Error Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "collapsed": true,
   "panels": [
    {
     "title": "Physical coding sublayer errors",
     "type": "table",
     "gridPos": { "h": 9, "w": 6, "x": 0, "y": 20 },
     "targets": [
      {
       "target": "aliasByNode(nonNegativeDerivative(brocade.fos.stats.ports.$Fabric.$Switch.$Porttype.$Slot.$Port.pcs), 5, 7, 8)"
      }
     ]
    },
    {
     "title": "Encoding OUT errors",
     "type": "table",
     "gridPos": { "h": 9, "w": 6, "x": 6, "y": 20 },
     "targets": [
      {
       "target": "aliasByNode(nonNegativeDerivative(brocade.fos.stats.ports.$Fabric.$Switch.$Porttype.$Slot.$Port.enc_out), 5, 7, 8)"
      }
     ]
    },
    {
     "title": "CRC errors",
     "type": "table",
     "gridPos": { "h": 9, "w": 6, "x": 12, "y": 20 },
     "targets": [
      {
       "target": "aliasByNode(nonNegativeDerivative(brocade.fos.stats.ports.$Fabric.$Switch.$Porttype.$Slot.$Port.crc-errors), 5, 7, 8)"
      }
     ]
    },
    {
     "title": "Invalid orderd sets",
     "type": "table",
     "gridPos": { "h": 9, "w": 6, "x": 18, "y": 20 },
     "targets": [
      {
       "target": "aliasByNode(nonNegativeDerivative(brocade.fos.stats.ports.$Fabric.$Switch.$Porttype.$Slot.$Port.inv_os), 5, 7, 8)"
      }
     ]
    },
    {
     "title": "Link failures",
     "type": "table",
     "gridPos": { "h": 9, "w": 6, "x": 0, "y": 29 },
     "targets": [
      {
       "target": "aliasByNode(nonNegativeDerivative(brocade.fos.stats.ports.$Fabric.$Switch.$Porttype.$Slot.$Port.link-failures), 5, 7, 8)"
      }
     ]
    },
    {
     "title": "Link reset IN",
     "type": "table",
     "gridPos": { "h": 9, "w": 6, "x": 6, "y": 29 },
     "targets": [
      {
       "target": "aliasByNode(nonNegativeDerivative(brocade.fos.stats.ports.$Fabric.$Switch.$Porttype.$Slot.$Port.lr_in), 5, 7, 8)"
      }
     ]
    },
    {
     "title": "Link reset OUT",
     "type": "table",
     "gridPos": { "h": 9, "w": 6, "x": 12, "y": 29 },
     "targets": [
      {
       "target": "aliasByNode(nonNegativeDerivative(brocade.fos.stats.ports.$Fabric.$Switch.$Porttype.$Slot.$Port.lr_out), 5, 7, 8)"
      }
     ]
    },
    {
     "title": "Loss of sync",
     "type": "table",
     "gridPos": { "h": 9, "w": 6, "x": 18, "y": 29 },
     "targets": [
      {
       "target": "aliasByNode(nonNegativeDerivative(brocade.fos.stats.ports.$Fabric.$Switch.$Porttype.$Slot.$Port.loss-of-sync), 5, 7, 8)"
      }
     ]
    },
    {
     "title": "Loss of signal",
     "type": "table",
     "gridPos": { "h": 9, "w": 6, "x": 0, "y": 38 },
     "targets": [
      {
       "target": "aliasByNode(nonNegativeDerivative(brocade.fos.stats.ports.$Fabric.$Switch.$Porttype.$Slot.$Port.loss-of-signal), 5, 7, 8)"
      }
     ]
    },
    {
     "title": "C3 discards",
     "type": "table",
     "gridPos": { "h": 9, "w": 6, "x": 6, "y": 38 },
     "targets": [
      {
       "target": "aliasByNode(nonNegativeDerivative(brocade.fos.stats.ports.$Fabric.$Switch.$Porttype.$Slot.$Port.class-3-discards), 5, 7, 8)"
      }
     ]
    },
    {
     "title": "C3 RXTO discards",
     "type": "table",
     "gridPos": { "h": 9, "w": 6, "x": 12, "y": 38 },
     "targets": [
      {
       "target": "aliasByNode(nonNegativeDerivative(brocade.fos.stats.ports.$Fabric.$Switch.$Porttype.$Slot.$Port.c3_rxto), 5, 7, 8)"
      }
     ]
    },
    {
     "title": "C3 TXTO discards",
     "type": "table",
     "gridPos": { "h": 9, "w": 6, "x": 18, "y": 38 },
     "targets": [
      {
       "target": "aliasByNode(nonNegativeDerivative(brocade.fos.stats.ports.$Fabric.$Switch.$Porttype.$Slot.$Port.c3_txto), 5, 7, 8)"
      }
     ]
    }
   ]
  },
  {
   "title": "Error Details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "collapsed": true,
   "panels": [
    {
     "title": "Physical coding sublayer errors",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 21 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "target": "aliasByNode(nonNegativeDerivative(brocade.fos.stats.ports.$Fabric.$Switch.$Porttype.$Slot.$Port.pcs), 5, 7, 8)"
      }
     ]
    },
    {
     "title": "Encoding out errors",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 21 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "target": "aliasByNode(nonNegativeDerivative(brocade.fos.stats.ports.$Fabric.$Switch.$Porttype.$Slot.$Port.enc_out), 5, 7, 8)"
      }
     ]
    },
    {
     "title": "CRC errors",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 21 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "target": "aliasByNode(nonNegativeDerivative(brocade.fos.stats.ports.$Fabric.$Switch.$Porttype.$Slot.$Port.crc-errors), 5, 7, 8)"
      }
     ]
    },
    {
     "title": "Invalid orderd sets",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 21 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "target": "aliasByNode(nonNegativeDerivative(brocade.fos.stats.ports.$Fabric.$Switch.$Porttype.$Slot.$Port.inv_os), 5, 7, 8)"
      }
     ]
    },
    {
     "title": "Link failures",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 29 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "target": "aliasByNode(nonNegativeDerivative(brocade.fos.stats.ports.$Fabric.$Switch.$Porttype.$Slot.$Port.link-failures), 5, 7, 8)"
      }
     ]
    },
    {
     "title": "Link resets IN",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 29 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "target": "aliasByNode(nonNegativeDerivative(brocade.fos.stats.ports.$Fabric.$Switch.$Porttype.$Slot.$Port.lr_in), 5, 7, 8)"
      }
     ]
    },
    {
     "title": "Link resets OUT",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 29 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "target": "aliasByNode(nonNegativeDerivative(brocade.fos.stats.ports.$Fabric.$Switch.$Porttype.$Slot.$Port.lr_out), 5, 7, 8)"
      }
     ]
    },
    {
     "title": "Loss of sync",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 29 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "target": "aliasByNode(nonNegativeDerivative(brocade.fos.stats.ports.$Fabric.$Switch.$Porttype.$Slot.$Port.loss-of-sync), 5, 7, 8)"
      }
     ]
    },
    {
     "title": "Loss of signal",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 37 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "target": "aliasByNode(nonNegativeDerivative(brocade.fos.stats.ports.$Fabric.$Switch.$Porttype.$Slot.$Port.loss-of-signal), 5, 7, 8)"
      }
     ]
    },
    {
     "title": "C3 discards",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 37 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "target": "aliasByNode(nonNegativeDerivative(brocade.fos.stats.ports.$Fabric.$Switch.$Porttype.$Slot.$Port.class-3-discards), 5, 7, 8)"
      }
     ]
    },
    {
     "title": "C3 RXTO discards",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 37 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "target": "aliasByNode(nonNegativeDerivative(brocade.fos.stats.ports.$Fabric.$Switch.$Porttype.$Slot.$Port.c3_rxto), 5, 7, 8)"
      }
     ]
    },
    {
     "title": "C3 TXTO discards",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 37 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "target": "aliasByNode(nonNegativeDerivative(brocade.fos.stats.ports.$Fabric.$Switch.$Porttype.$Slot.$Port.c3_txto), 5, 7, 8)"
      }
     ]
    }
   ]
  },
  {
   "title": "SFP Details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "collapsed": true,
   "panels": [
    {
     "title": "SPF RX power in dBm",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
     "yaxes": [
      { "format": "dBm" }
     ],
     "targets": [
      {
       "target": "aliasByNode(brocade.fos.stats.ports.$Fabric.$Switch.$Porttype.$Slot.$Port.rx-power-dbm, 5, 7, 8)"
      }
     ]
    },
    {
     "title": "SPF TX power in dBm",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
     "yaxes": [
      { "format": "dBm" }
     ],
     "targets": [
      {
       "target": "aliasByNode(brocade.fos.stats.ports.$Fabric.$Switch.$Porttype.$Slot.$Port.tx-power-dbm, 5, 7, 8)"
      }
     ]
    },
    {
     "title": "SPF RX power in milliwatt",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 30 },
     "yaxes": [
      { "format": "mamp" }
     ],
     "targets": [
      {
       "target": "aliasByNode(brocade.fos.stats.ports.$Fabric.$Switch.$Porttype.$Slot.$Port.rx-power, 5, 7, 8)"
      }
     ]
    },
    {
     "title": "SPF TX power in milliwatt",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 30 },
     "yaxes": [
      { "format": "mamp" }
     ],
     "targets": [
      {
       "target": "aliasByNode(brocade.fos.stats.ports.$Fabric.$Switch.$Porttype.$Slot.$Port.tx-power, 5, 7, 8)"
      }
     ]
    }
   ]
  }
 ]
}