{
 "title": "Brocade: fos2graphite statistics",
 "tags": [ "fos2graphite" ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "Datasource", "query": "graphite" }
  ]
 },
 "panels": [
  {
   "title": "HTTP response time fiberchannel query",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "target": "aliasByNode(brocade.fos2graphite.stats.query.*.fibrechannel.duration, 4)"
    }
   ]
  },
  {
   "title": "HTTP response time fiberchannel statistics query",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "target": "aliasByNode(brocade.fos2graphite.stats.query.*.fibrechannel-statistics.duration, 4)"
    }
   ]
  },
  {
   "title": "HTTP response time brocade-media query",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "target": "aliasByNode(brocade.fos2graphite.stats.query.*.brocade-media.duration, 4)"
    }
   ]
  },
  {
   "title": "HTTP response time system-resources query",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "target": "aliasByNode(brocade.fos2graphite.stats.query.*.system-resources.duration, 4)"
    }
   ]
  },
  {
   "title": "HTTP response time name-server query",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "target": "aliasByNode(brocade.fos2graphite.stats.query.*.brocade-nameserver.duration, 4)"
    }
   ]
  }
 ]
}