{
 "title": "Brocade: ISL Overview (Realtime)",
 "tags": [
  "Brocade",
  "Realtime"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "Fabric", "query": "brocade.fos.stats.ports.*" },
   {
    "name": "Switch",
    "query": "brocade.fos.stats.ports.$Fabric.*"
   }
  ]
 },
 "panels": [
  {
   "title": "Performance: Long distance ISLs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "RX throughput of long distance ISLs for $Fabric / $Switch",
   "type": "graph",
   "gridPos": { "h": 9, "w": 9, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "target": "sortByMaxima(aliasByNode(scaleToSeconds(nonNegativeDerivative(brocade.fos.perf.ports.$Fabric.$Switch.LS_PORT.*.*.in-octets), 1), 5, 7, 8))"
    }
   ]
  },
  {
   "title": "RX throughput of long distance ISLs for $Fabric / $Switch",
   "type": "stat",
   "gridPos": { "h": 9, "w": 3, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "averageSeries(scaleToSeconds(nonNegativeDerivative(brocade.fos.perf.ports.$Fabric.$Switch.LS_PORT.*.*.in-octets), 1))"
    }
   ]
  },
  {
   "title": "TX throughput of long distance ISLs for $Fabric / $Switch",
   "type": "graph",
   "gridPos": { "h": 9, "w": 9, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "target": "sortByMaxima(aliasByNode(scaleToSeconds(nonNegativeDerivative(brocade.fos.perf.ports.$Fabric.$Switch.LS_PORT.*.*.out-octets), 1), 5, 7, 8))"
    }
   ]
  },
  {
   "title": "RX throughput of long distance ISLs for $Fabric / $Switch",
   "type": "stat",
   "gridPos": { "h": 9, "w": 3, "x": 21, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "averageSeries(scaleToSeconds(nonNegativeDerivative(brocade.fos.perf.ports.$Fabric.$Switch.LS_PORT.*.*.out-octets), 1))"
    }
   ]
  },
  {
   "title": "Errors: Long distance ISLs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "panels": [
    {
     "title": "PCS errors for $Fabric / $Switch",
     "type": "table-old",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 11 },
     "targets": [
      {
       "target": "aliasByNode(highestAverage(nonNegativeDerivative(brocade.fos.stats.ports.$Fabric.$Switch.LS_PORT.*.*.pcs), 20), 5, 7, 8)"
      }
     ]
    },
    {
     "title": "Encoding Out errors for $Fabric / $Switch",
     "type": "table-old",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 11 },
     "targets": [
      {
       "target": "aliasByNode(highestAverage(nonNegativeDerivative(brocade.fos.stats.ports.$Fabric.$Switch.LS_PORT.*.*.enc_out), 20), 5, 7, 8)"
      }
     ]
    },
    {
     "title": "CRC errors for $Fabric / $Switch",
     "type": "table-old",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 11 },
     "targets": [
      {
       "target": "aliasByNode(highestAverage(nonNegativeDerivative(brocade.fos.stats.ports.$Fabric.$Switch.LS_PORT.*.*.crc-errors), 20), 5, 7, 8)"
      }
     ]
    },
    {
     "title": "Invalid Ordered Set for $Fabric / $Switch",
     "type": "table-old",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 11 },
     "targets": [
      {
       "target": "aliasByNode(highestAverage(nonNegativeDerivative(brocade.fos.stats.ports.$Fabric.$Switch.LS_PORT.*.*.inv_os), 20), 5, 7, 8)"
      }
     ]
    },
    {
     "title": "Link failures for $Fabric / $Switch",
     "type": "table-old",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 19 },
     "targets": [
      {
       "target": "aliasByNode(highestAverage(nonNegativeDerivative(brocade.fos.stats.ports.$Fabric.$Switch.LS_PORT.*.*.link-failures), 20), 5, 7, 8)"
      }
     ]
    },
    {
     "title": "Link reset IN for $Fabric / $Switch",
     "type": "table-old",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 19 },
     "targets": [
      {
       "target": "aliasByNode(highestAverage(nonNegativeDerivative(brocade.fos.stats.ports.$Fabric.$Switch.LS_PORT.*.*.lr_in), 20), 5, 7, 8)"
      }
     ]
    },
    {
     "title": "Link reset OUT for $Fabric / $Switch",
     "type": "table-old",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 19 },
     "targets": [
      {
       "target": "aliasByNode(highestAverage(nonNegativeDerivative(brocade.fos.stats.ports.$Fabric.$Switch.LS_PORT.*.*.lr_out), 20), 5, 7, 8)"
      }
     ]
    },
    {
     "title": "Loss of sync for $Fabric / $Switch",
     "type": "table-old",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 19 },
     "targets": [
      {
       "target": "aliasByNode(highestAverage(nonNegativeDerivative(brocade.fos.stats.ports.$Fabric.$Switch.LS_PORT.*.*.loss-of-sync), 20), 5, 7, 8)"
      }
     ]
    },
    {
     "title": "Discards for $Fabric / $Switch",
     "type": "table-old",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 27 },
     "targets": [
      {
       "target": "aliasByNode(highestAverage(nonNegativeDerivative(brocade.fos.stats.ports.$Fabric.$Switch.LS_PORT.*.*.class-3-discards), 20), 5, 7, 8)"
      }
     ]
    },
    {
     "title": "Discards TXTO for $Fabric / $Switch",
     "type": "table-old",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 27 },
     "targets": [
      {
       "target": "aliasByNode(highestAverage(nonNegativeDerivative(brocade.fos.stats.ports.$Fabric.$Switch.LS_PORT.*.*.c3_txto), 20), 5, 7, 8)"
      }
     ]
    },
    {
     "title": "Discards RXTO for $Fabric / $Switch",
     "type": "table-old",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 27 },
     "targets": [
      {
       "target": "aliasByNode(highestAverage(nonNegativeDerivative(brocade.fos.stats.ports.$Fabric.$Switch.LS_PORT.*.*.c3_rxto), 20), 5, 7, 8)"
      }
     ]
    }
   ]
  },
  {
   "title": "Performance: Standard distance ISLs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true,
   "panels": [
    {
     "title": "RX throughput of ISLs for $Fabric / $Switch",
     "type": "graph",
     "gridPos": { "h": 9, "w": 9, "x": 0, "y": 12 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "target": "sortByMaxima(aliasByNode(scaleToSeconds(nonNegativeDerivative(brocade.fos.perf.ports.$Fabric.$Switch.E_PORT.*.*.in-octets), 1), 5, 7, 8))"
      }
     ]
    },
    {
     "title": "RX throughput of ISLs for $Fabric / $Switch",
     "type": "stat",
     "gridPos": { "h": 9, "w": 3, "x": 9, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "target": "averageSeries(scaleToSeconds(nonNegativeDerivative(brocade.fos.perf.ports.$Fabric.$Switch.E_PORT.*.*.in-octets), 1))"
      }
     ]
    },
    {
     "title": "TX throughput of ISLs for $Fabric / $Switch",
     "type": "graph",
     "gridPos": { "h": 9, "w": 9, "x": 12, "y": 12 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "target": "sortByMaxima(aliasByNode(scaleToSeconds(nonNegativeDerivative(brocade.fos.perf.ports.$Fabric.$Switch.E_PORT.*.*.out-octets), 1), 5, 7, 8))"
      }
     ]
    },
    {
     "title": "RX throughput of ISLs for $Fabric / $Switch",
     "type": "stat",
     "gridPos": { "h": 9, "w": 3, "x": 21, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "target": "averageSeries(scaleToSeconds(nonNegativeDerivative(brocade.fos.perf.ports.$Fabric.$Switch.E_PORT.*.*.out-octets), 1))"
      }
     ]
    }
   ]
  },
  {
   "title": "Errors: Standard distance ISLs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "collapsed": true,
   "panels": [
    {
     "title": "PCS errors for $Fabric / $Switch",
     "type": "table-old",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 13 },
     "targets": [
      {
       "target": "aliasByNode(highestAverage(nonNegativeDerivative(brocade.fos.stats.ports.$Fabric.$Switch.E_PORT.*.*.pcs), 20), 5, 7, 8)"
      }
     ]
    },
    {
     "title": "Encoding Out errors for $Fabric / $Switch",
     "type": "table-old",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 13 },
     "targets": [
      {
       "target": "aliasByNode(highestAverage(nonNegativeDerivative(brocade.fos.stats.ports.$Fabric.$Switch.E_PORT.*.*.enc_out), 20), 5, 7, 8)"
      }
     ]
    },
    {
     "title": "CRC errors for $Fabric / $Switch",
     "type": "table-old",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 13 },
     "targets": [
      {
       "target": "aliasByNode(highestAverage(nonNegativeDerivative(brocade.fos.stats.ports.$Fabric.$Switch.E_PORT.*.*.crc-errors), 20), 5, 7, 8)"
      }
     ]
    },
    {
     "title": "Invalid Ordered Set for $Fabric / $Switch",
     "type": "table-old",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 13 },
     "targets": [
      {
       "target": "aliasByNode(highestAverage(nonNegativeDerivative(brocade.fos.stats.ports.$Fabric.$Switch.E_PORT.*.*.inv_os), 20), 5, 7, 8)"
      }
     ]
    },
    {
     "title": "Link failures for $Fabric / $Switch",
     "type": "table-old",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 21 },
     "targets": [
      {
       "target": "aliasByNode(highestAverage(nonNegativeDerivative(brocade.fos.stats.ports.$Fabric.$Switch.E_PORT.*.*.link-failures), 20), 5, 7, 8)"
      }
     ]
    },
    {
     "title": "Link reset IN for $Fabric / $Switch",
     "type": "table-old",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 21 },
     "targets": [
      {
       "target": "aliasByNode(highestAverage(nonNegativeDerivative(brocade.fos.stats.ports.$Fabric.$Switch.E_PORT.*.*.lr_in), 20), 5, 7, 8)"
      }
     ]
    },
    {
     "title": "Link reset OUT for $Fabric / $Switch",
     "type": "table-old",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 21 },
     "targets": [
      {
       "target": "aliasByNode(highestAverage(nonNegativeDerivative(brocade.fos.stats.ports.$Fabric.$Switch.E_PORT.*.*.lr_out), 20), 5, 7, 8)"
      }
     ]
    },
    {
     "title": "Loss of sync for $Fabric / $Switch",
     "type": "table-old",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 21 },
     "targets": [
      {
       "target": "aliasByNode(highestAverage(nonNegativeDerivative(brocade.fos.stats.ports.$Fabric.$Switch.E_PORT.*.*.loss-of-sync), 20), 5, 7, 8)"
      }
     ]
    },
    {
     "title": "Discards for $Fabric / $Switch",
     "type": "table-old",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 29 },
     "targets": [
      {
       "target": "aliasByNode(highestAverage(nonNegativeDerivative(brocade.fos.stats.ports.$Fabric.$Switch.E_PORT.*.*.class-3-discards), 20), 5, 7, 8)"
      }
     ]
    },
    {
     "title": "Discards TXTO for $Fabric / $Switch",
     "type": "table-old",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 29 },
     "targets": [
      {
       "target": "aliasByNode(highestAverage(nonNegativeDerivative(brocade.fos.stats.ports.$Fabric.$Switch.E_PORT.*.*.c3_txto), 20), 5, 7, 8)"
      }
     ]
    },
    {
     "title": "Discards RXTO for $Fabric / $Switch",
     "type": "table-old",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 29 },
     "targets": [
      {
       "target": "aliasByNode(highestAverage(nonNegativeDerivative(brocade.fos.stats.ports.$Fabric.$Switch.E_PORT.*.*.c3_rxto), 20), 5, 7, 8)"
      }
     ]
    }
   ]
  }
 ]
}