{
 "title": "Brocade: Initiator / Target Details",
 "tags": [
  "Brocade",
  "Realtime"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "Fabric", "query": "brocade.fos.stats.devices.*" },
   {
    "name": "Type",
    "query": "brocade.fos.stats.devices.$Fabric.*"
   },
   {
    "name": "Device",
    "query": "brocade.fos.stats.devices.$Fabric.$Type.*"
   }
  ]
 },
 "panels": [
  { "title": "Performance Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Stacked RX Throughput",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "target": "aliasByNode(scaleToSeconds(nonNegativeDerivative(brocade.fos.perf.devices.$Fabric.$Type.$Device.in-octets), 1), 6, 7)"
    }
   ]
  },
  {
   "title": "Stacked TX Throughput",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "target": "aliasByNode(scaleToSeconds(nonNegativeDerivative(brocade.fos.perf.devices.$Fabric.$Type.$Device.out-octets), 1), 6, 7)"
    }
   ]
  },
  {
   "title": "RX Throughput Details",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "target": "aliasByNode(scaleToSeconds(nonNegativeDerivative(brocade.fos.perf.devices.$Fabric.$Type.$Device.in-octets), 1), 6, 7)"
    }
   ]
  },
  {
   "title": "TX Throughput Details",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "target": "aliasByNode(scaleToSeconds(nonNegativeDerivative(brocade.fos.perf.devices.$Fabric.$Type.$Device.out-octets), 1), 6, 7)"
    }
   ]
  },
  {
   "title": "Performance Details $Device",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "repeat": "Device",
   "collapsed": true,
   "panels": [
    {
     "title": "RX / TX Throughput",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "target": "alias(scaleToSeconds(nonNegativeDerivative(brocade.fos.perf.devices.$Fabric.$Type.$Device.out-octets), 1), 'TX')"
      },
      {
       "target": "alias(scaleToSeconds(nonNegativeDerivative(brocade.fos.perf.devices.$Fabric.$Type.$Device.in-octets), 1), 'RX')"
      }
     ]
    },
    {
     "title": "RX / TX Throughput",
     "type": "grafana-piechart-panel",
     "gridPos": { "h": 8, "w": 3, "x": 12, "y": 18 },
     "format": "Bps",
     "valueName": "current",
     "targets": [
      {
       "target": "alias(scaleToSeconds(nonNegativeDerivative(brocade.fos.perf.devices.$Fabric.$Type.$Device.in-octets), 1), 'RX')"
      },
      {
       "target": "alias(scaleToSeconds(nonNegativeDerivative(brocade.fos.perf.devices.$Fabric.$Type.$Device.out-octets), 1), 'TX')"
      }
     ]
    },
    {
     "title": "RX / TX Throughput",
     "type": "graph",
     "gridPos": { "h": 8, "w": 9, "x": 15, "y": 18 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "refCount": 1,
       "target": "alias(asPercent(scaleToSeconds(nonNegativeDerivative(brocade.fos.perf.devices.$Fabric.$Type.$Device.in-octets), 1), #A), 'RX')",
       "targetFull": "alias(asPercent(scaleToSeconds(nonNegativeDerivative(brocade.fos.perf.devices.$Fabric.$Type.$Device.in-octets), 1), sumSeries(scaleToSeconds(nonNegativeDerivative(brocade.fos.perf.devices.$Fabric.$Type.$Device.*-octets), 1))), 'RX')"
      },
      {
       "target": "alias(asPercent(scaleToSeconds(nonNegativeDerivative(brocade.fos.perf.devices.$Fabric.$Type.$Device.out-octets), 1), #A), 'TX')",
       "targetFull": "alias(asPercent(scaleToSeconds(nonNegativeDerivative(brocade.fos.perf.devices.$Fabric.$Type.$Device.out-octets), 1), sumSeries(scaleToSeconds(nonNegativeDerivative(brocade.fos.perf.devices.$Fabric.$Type.$Device.*-octets), 1))), 'TX')"
      }
     ]
    },
    {
     "title": "Physical Errors",
     "type": "table",
     "gridPos": { "h": 11, "w": 8, "x": 0, "y": 26 },
     "targets": [
      {
       "target": "aliasByMetric(nonNegativeDerivative(brocade.fos.stats.devices.$Fabric.$Type.$Device.crc-errors))"
      },
      {
       "target": "aliasByMetric(nonNegativeDerivative(brocade.fos.stats.devices.$Fabric.$Type.$Device.itw))"
      },
      {
       "target": "aliasByMetric(nonNegativeDerivative(brocade.fos.stats.devices.$Fabric.$Type.$Device.bad-eofs-received))"
      },
      {
       "target": "aliasByMetric(nonNegativeDerivative(brocade.fos.stats.devices.$Fabric.$Type.$Device.address-errors))"
      },
      {
       "target": "aliasByMetric(nonNegativeDerivative(brocade.fos.stats.devices.$Fabric.$Type.$Device.delimiter-errors))"
      },
      {
       "target": "aliasByMetric(nonNegativeDerivative(brocade.fos.stats.devices.$Fabric.$Type.$Device.in-crc-errors))"
      },
      {
       "target": "aliasByMetric(nonNegativeDerivative(brocade.fos.stats.devices.$Fabric.$Type.$Device.enc_out))"
      },
      {
       "target": "aliasByMetric(nonNegativeDerivative(brocade.fos.stats.devices.$Fabric.$Type.$Device.pcs))"
      },
      {
       "target": "aliasByMetric(nonNegativeDerivative(brocade.fos.stats.devices.$Fabric.$Type.$Device.pcs))"
      }
     ]
    },
    {
     "title": "Link Errors",
     "type": "table",
     "gridPos": { "h": 11, "w": 8, "x": 8, "y": 26 },
     "targets": [
      {
       "target": "aliasByMetric(nonNegativeDerivative(brocade.fos.stats.devices.$Fabric.$Type.$Device.link-failures))"
      },
      {
       "target": "aliasByMetric(nonNegativeDerivative(brocade.fos.stats.devices.$Fabric.$Type.$Device.loss-of-signal))"
      },
      {
       "target": "aliasByMetric(nonNegativeDerivative(brocade.fos.stats.devices.$Fabric.$Type.$Device.loss-of-sync))"
      },
      {
       "target": "aliasByMetric(nonNegativeDerivative(brocade.fos.stats.devices.$Fabric.$Type.$Device.lr_in))"
      },
      {
       "target": "aliasByMetric(nonNegativeDerivative(brocade.fos.stats.devices.$Fabric.$Type.$Device.lr_out))"
      }
     ]
    },
    {
     "title": "Discard Errors",
     "type": "table",
     "gridPos": { "h": 11, "w": 8, "x": 16, "y": 26 },
     "targets": [
      {
       "target": "aliasByMetric(nonNegativeDerivative(brocade.fos.stats.devices.$Fabric.$Type.$Device.class-3-discards))"
      },
      {
       "target": "aliasByMetric(nonNegativeDerivative(brocade.fos.stats.devices.$Fabric.$Type.$Device.c3_rxto))"
      },
      {
       "target": "aliasByMetric(nonNegativeDerivative(brocade.fos.stats.devices.$Fabric.$Type.$Device.c3_txto))"
      }
     ]
    },
    {
     "title": "SFP RX Power of $Device",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 37 },
     "yaxes": [
      { "format": "dBm" }
     ],
     "targets": [
      {
       "target": "aliasByNode(brocade.fos.stats.devices.$Fabric.$Type.$Device.rx-power-dbm, 6)"
      }
     ]
    },
    {
     "title": "SFP TX Power of $Device",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 37 },
     "yaxes": [
      { "format": "dBm" }
     ],
     "targets": [
      {
       "target": "aliasByNode(brocade.fos.stats.devices.$Fabric.$Type.$Device.tx-power-dbm, 6)"
      }
     ]
    }
   ]
  },
  {
   "title": "Performance Details $Device",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true,
   "panels": [
    {
     "title": "RX / TX Throughput",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "target": "alias(scaleToSeconds(nonNegativeDerivative(brocade.fos.perf.devices.$Fabric.$Type.$Device.out-octets), 1), 'TX')"
      },
      {
       "target": "alias(scaleToSeconds(nonNegativeDerivative(brocade.fos.perf.devices.$Fabric.$Type.$Device.in-octets), 1), 'RX')"
      }
     ]
    },
    {
     "title": "RX / TX Throughput",
     "type": "grafana-piechart-panel",
     "gridPos": { "h": 8, "w": 3, "x": 12, "y": 18 },
     "format": "Bps",
     "valueName": "current",
     "targets": [
      {
       "target": "alias(scaleToSeconds(nonNegativeDerivative(brocade.fos.perf.devices.$Fabric.$Type.$Device.in-octets), 1), 'RX')"
      },
      {
       "target": "alias(scaleToSeconds(nonNegativeDerivative(brocade.fos.perf.devices.$Fabric.$Type.$Device.out-octets), 1), 'TX')"
      }
     ]
    },
    {
     "title": "RX / TX Throughput",
     "type": "graph",
     "gridPos": { "h": 8, "w": 9, "x": 15, "y": 18 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "refCount": 1,
       "target": "alias(asPercent(scaleToSeconds(nonNegativeDerivative(brocade.fos.perf.devices.$Fabric.$Type.$Device.in-octets), 1), #A), 'RX')",
       "targetFull": "alias(asPercent(scaleToSeconds(nonNegativeDerivative(brocade.fos.perf.devices.$Fabric.$Type.$Device.in-octets), 1), sumSeries(scaleToSeconds(nonNegativeDerivative(brocade.fos.perf.devices.$Fabric.$Type.$Device.*-octets), 1))), 'RX')"
      },
      {
       "target": "alias(asPercent(scaleToSeconds(nonNegativeDerivative(brocade.fos.perf.devices.$Fabric.$Type.$Device.out-octets), 1), #A), 'TX')",
       "targetFull": "alias(asPercent(scaleToSeconds(nonNegativeDerivative(brocade.fos.perf.devices.$Fabric.$Type.$Device.out-octets), 1), sumSeries(scaleToSeconds(nonNegativeDerivative(brocade.fos.perf.devices.$Fabric.$Type.$Device.*-octets), 1))), 'TX')"
      }
     ]
    },
    {
     "title": "Physical Errors",
     "type": "table",
     "gridPos": { "h": 11, "w": 8, "x": 0, "y": 26 },
     "targets": [
      {
       "target": "aliasByMetric(nonNegativeDerivative(brocade.fos.stats.devices.$Fabric.$Type.$Device.crc-errors))"
      },
      {
       "target": "aliasByMetric(nonNegativeDerivative(brocade.fos.stats.devices.$Fabric.$Type.$Device.itw))"
      },
      {
       "target": "aliasByMetric(nonNegativeDerivative(brocade.fos.stats.devices.$Fabric.$Type.$Device.bad-eofs-received))"
      },
      {
       "target": "aliasByMetric(nonNegativeDerivative(brocade.fos.stats.devices.$Fabric.$Type.$Device.address-errors))"
      },
      {
       "target": "aliasByMetric(nonNegativeDerivative(brocade.fos.stats.devices.$Fabric.$Type.$Device.delimiter-errors))"
      },
      {
       "target": "aliasByMetric(nonNegativeDerivative(brocade.fos.stats.devices.$Fabric.$Type.$Device.in-crc-errors))"
      },
      {
       "target": "aliasByMetric(nonNegativeDerivative(brocade.fos.stats.devices.$Fabric.$Type.$Device.enc_out))"
      },
      {
       "target": "aliasByMetric(nonNegativeDerivative(brocade.fos.stats.devices.$Fabric.$Type.$Device.pcs))"
      },
      {
       "target": "aliasByMetric(nonNegativeDerivative(brocade.fos.stats.devices.$Fabric.$Type.$Device.pcs))"
      }
     ]
    },
    {
     "title": "Link Errors",
     "type": "table",
     "gridPos": { "h": 11, "w": 8, "x": 8, "y": 26 },
     "targets": [
      {
       "target": "aliasByMetric(nonNegativeDerivative(brocade.fos.stats.devices.$Fabric.$Type.$Device.link-failures))"
      },
      {
       "target": "aliasByMetric(nonNegativeDerivative(brocade.fos.stats.devices.$Fabric.$Type.$Device.loss-of-signal))"
      },
      {
       "target": "aliasByMetric(nonNegativeDerivative(brocade.fos.stats.devices.$Fabric.$Type.$Device.loss-of-sync))"
      },
      {
       "target": "aliasByMetric(nonNegativeDerivative(brocade.fos.stats.devices.$Fabric.$Type.$Device.lr_in))"
      },
      {
       "target": "aliasByMetric(nonNegativeDerivative(brocade.fos.stats.devices.$Fabric.$Type.$Device.lr_out))"
      }
     ]
    },
    {
     "title": "Discard Errors",
     "type": "table",
     "gridPos": { "h": 11, "w": 8, "x": 16, "y": 26 },
     "targets": [
      {
       "target": "aliasByMetric(nonNegativeDerivative(brocade.fos.stats.devices.$Fabric.$Type.$Device.class-3-discards))"
      },
      {
       "target": "aliasByMetric(nonNegativeDerivative(brocade.fos.stats.devices.$Fabric.$Type.$Device.c3_rxto))"
      },
      {
       "target": "aliasByMetric(nonNegativeDerivative(brocade.fos.stats.devices.$Fabric.$Type.$Device.c3_txto))"
      }
     ]
    },
    {
     "title": "SFP RX Power of $Device",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 37 },
     "yaxes": [
      { "format": "dBm" }
     ],
     "targets": [
      {
       "target": "aliasByNode(brocade.fos.stats.devices.$Fabric.$Type.$Device.rx-power-dbm, 6)"
      }
     ]
    },
    {
     "title": "SFP TX Power of $Device",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 37 },
     "yaxes": [
      { "format": "dBm" }
     ],
     "targets": [
      {
       "target": "aliasByNode(brocade.fos.stats.devices.$Fabric.$Type.$Device.tx-power-dbm, 6)"
      }
     ]
    }
   ]
  }
 ]
}