{
 "title": "Brocade: Switch Overview (Realtime) - Prometheus",
 "description": "CPU, Memory and Flash Statistics",
 "tags": [
  "Brocade",
  "Realtime",
  "Prometheus"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "Fabric", "query": { "query": "label_values(fabric)" } },
   {
    "name": "Switch",
    "query": {
     "query": "label_values(fosswitch_cpu_usage{fabric=~\"$Fabric\"}, switch)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "CPU utilization $Fabric / $Switch",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 16, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "fosswitch_cpu_usage{fabric=~\"$Fabric\",switch=~\"$Switch\"}",
     "legendFormat": "{{switch}}"
    }
   ]
  },
  {
   "title": "Current CPU utilization $Fabric / $Switch",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "fosswitch_cpu_usage{fabric=~\"$Fabric\",switch=~\"$Switch\"}",
     "legendFormat": "{{switch}}"
    }
   ]
  },
  {
   "title": "Memory utilization $Fabric / $Switch",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 16, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "fosswitch_memory_usage{fabric=~\"$Fabric\",switch=~\"$Switch\"}",
     "legendFormat": "{{switch}}"
    }
   ]
  },
  {
   "title": "Current Memory utilization $Fabric / $Switch",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "fosswitch_memory_usage{fabric=~\"$Fabric\",switch=~\"$Switch\"}",
     "legendFormat": "{{switch}}"
    }
   ]
  },
  {
   "title": "Flash utilization $Fabric / $Switch",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 16, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "fosswitch_flash_usage{fabric=~\"$Fabric\",switch=~\"$Switch\"}",
     "legendFormat": "{{switch}}"
    }
   ]
  },
  {
   "title": "Current flash utilization $Fabric / $Switch",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "fosswitch_flash_usage{fabric=~\"$Fabric\",switch=~\"$Switch\"}",
     "legendFormat": "{{switch}}"
    }
   ]
  }
 ]
}