{
 "title": "Brocade: ISL Overview (Realtime) - Prometheus",
 "tags": [
  "Brocade",
  "Realtime",
  "Prometheus"
 ],
 "time": { "from": "now-12h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Fabric",
    "query": {
     "query": "label_values(fosports_rx_power{}, fabric)"
    }
   },
   {
    "name": "Switch",
    "query": {
     "query": "label_values(fosports_rx_power{fabric=~\"$Fabric\"}, switch)"
    }
   },
   {
    "name": "errorcounter",
    "query": "Physical coding sublayer errors : pcs, Encoding OUT errors : enc_out, CRC errors : crc_errors, Invalid ordered set : inv_os, Link failures : link_failures, Link reset IN : lr_in, Link reset OUT : lr_out, Loss of sync : loss_of_sync, Loss of signal : loss_of_signal, C3 discards : class_3_discards, C3 RXTO discards : c3_rxto, C3 TXTO discards : c3_txto"
   }
  ]
 },
 "panels": [
  {
   "title": "Performance: Long distance ISLs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "RX throughput of long distance ISLs for $Fabric / $Switch",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 9, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(fosports_in_octets{fabric=~\"$Fabric\",switch=~\"$Switch\",porttype=\"LS_PORT\"})",
     "legendFormat": "{{switch}}.{{slot}}.{{port}}"
    }
   ]
  },
  {
   "title": "RX throughput of long distance ISLs for $Fabric / $Switch",
   "type": "stat",
   "gridPos": { "h": 9, "w": 3, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(rate(fosports_in_octets{fabric=~\"$Fabric\",switch=~\"$Switch\",porttype=\"LS_PORT\"}))",
     "legendFormat": "RX throughput"
    }
   ]
  },
  {
   "title": "TX throughput of long distance ISLs for $Fabric / $Switch",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 9, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(fosports_out_octets{fabric=~\"$Fabric\",switch=~\"$Switch\",porttype=\"LS_PORT\"})",
     "legendFormat": "{{switch}}.{{slot}}.{{port}}"
    }
   ]
  },
  {
   "title": "TX throughput of long distance ISLs for $Fabric / $Switch",
   "type": "stat",
   "gridPos": { "h": 9, "w": 3, "x": 21, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(rate(fosports_out_octets{fabric=~\"$Fabric\",switch=~\"$Switch\",porttype=\"LS_PORT\"}))",
     "legendFormat": "TX throughput"
    }
   ]
  },
  {
   "title": "RX port usage % of long distance ISLs for $Fabric / $Switch",
   "type": "timeseries",
   "description": "maximum usable approx. 80%",
   "gridPos": { "h": 9, "w": 9, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "rate(fosports_in_octets{fabric=~\"$Fabric\",switch=~\"$Switch\",porttype=\"LS_PORT\"}) / ignoring(category) (fosports_portspeed /8)",
     "legendFormat": "{{switch}}.{{slot}}.{{port}}"
    }
   ]
  },
  {
   "title": "RX port usage % of long distance ISLs for $Fabric / $Switch",
   "type": "stat",
   "gridPos": { "h": 9, "w": 3, "x": 9, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(rate(fosports_in_octets{fabric=~\"$Fabric\",switch=~\"$Switch\",porttype=\"LS_PORT\"}) / ignoring(category) (fosports_portspeed /8))",
     "legendFormat": "RX throughput"
    }
   ]
  },
  {
   "title": "TX port usage % of long distance ISLs for $Fabric / $Switch",
   "type": "timeseries",
   "description": "maximum usable approx. 80%",
   "gridPos": { "h": 9, "w": 9, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "rate(fosports_out_octets{fabric=~\"$Fabric\",switch=~\"$Switch\",porttype=\"LS_PORT\"}) / ignoring(category) (fosports_portspeed /8)",
     "legendFormat": "{{switch}}.{{slot}}.{{port}}"
    }
   ]
  },
  {
   "title": "TX port usage % of long distance ISLs for $Fabric / $Switch",
   "type": "stat",
   "gridPos": { "h": 9, "w": 3, "x": 21, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(rate(fosports_out_octets{fabric=~\"$Fabric\",switch=~\"$Switch\",porttype=\"LS_PORT\"}) / ignoring(category) (fosports_portspeed /8))",
     "legendFormat": "TX throughput"
    }
   ]
  },
  {
   "title": "Errors: Long distance ISLs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "$errorcounter for $Fabric / $Switch",
     "type": "table",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 11 },
     "repeat": "errorcounter",
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(fosports_$errorcounter{fabric=~\"$Fabric\",switch=~\"$Switch\",porttype=\"LS_PORT\"})",
       "legendFormat": "{{switch}}.{{slot}}.{{port}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Performance: Standard distance ISLs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "targets": [
    {}
   ]
  },
  {
   "title": "RX throughput of ISLs for $Fabric / $Switch",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 9, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(fosports_in_octets{fabric=~\"$Fabric\",switch=~\"$Switch\",porttype=\"E_PORT\"})",
     "legendFormat": "{{switch}}.{{slot}}.{{port}}"
    }
   ]
  },
  {
   "title": "RX throughput of ISLs for $Fabric / $Switch",
   "type": "stat",
   "gridPos": { "h": 9, "w": 3, "x": 9, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(rate(fosports_in_octets{fabric=~\"$Fabric\",switch=~\"$Switch\",porttype=\"E_PORT\"}))",
     "legendFormat": "RX throughput"
    }
   ]
  },
  {
   "title": "TX throughput of ISLs for $Fabric / $Switch",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 9, "x": 12, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(fosports_out_octets{fabric=~\"$Fabric\",switch=~\"$Switch\",porttype=\"E_PORT\"})",
     "legendFormat": "{{switch}}.{{slot}}.{{port}}"
    }
   ]
  },
  {
   "title": "TX throughput of ISLs for $Fabric / $Switch",
   "type": "stat",
   "gridPos": { "h": 9, "w": 3, "x": 21, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(rate(fosports_out_octets{fabric=~\"$Fabric\",switch=~\"$Switch\",porttype=\"E_PORT\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RX port usage % of ISLs for $Fabric / $Switch",
   "type": "timeseries",
   "description": "maximum usable approx. 80%",
   "gridPos": { "h": 9, "w": 9, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "rate(fosports_in_octets{fabric=~\"$Fabric\",switch=~\"$Switch\",porttype=\"E_PORT\"}) / ignoring(category) (fosports_portspeed /8)",
     "legendFormat": "{{switch}}.{{slot}}.{{port}}"
    }
   ]
  },
  {
   "title": "RX port usage % of ISLs for $Fabric / $Switch",
   "type": "stat",
   "gridPos": { "h": 9, "w": 3, "x": 9, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(rate(fosports_in_octets{fabric=~\"$Fabric\",switch=~\"$Switch\",porttype=\"E_PORT\"}) / ignoring(category) (fosports_portspeed /8))",
     "legendFormat": "RX throughput"
    }
   ]
  },
  {
   "title": "TX port usage % of ISLs for $Fabric / $Switch",
   "type": "timeseries",
   "description": "maximum usable approx. 80%",
   "gridPos": { "h": 9, "w": 9, "x": 12, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "rate(fosports_out_octets{fabric=~\"$Fabric\",switch=~\"$Switch\",porttype=\"E_PORT\"}) / ignoring(category) (fosports_portspeed /8)",
     "legendFormat": "{{switch}}.{{slot}}.{{port}}"
    }
   ]
  },
  {
   "title": "TX port usage % of ISLs for $Fabric / $Switch",
   "type": "stat",
   "gridPos": { "h": 9, "w": 3, "x": 21, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(rate(fosports_out_octets{fabric=~\"$Fabric\",switch=~\"$Switch\",porttype=\"E_PORT\"}) / ignoring(category) (fosports_portspeed /8))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Errors: Standard distance ISLs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "$errorcounter for $Fabric / $Switch",
     "type": "table",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 22 },
     "repeat": "errorcounter",
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(fosports_$errorcounter{fabric=~\"$Fabric\",switch=~\"$Switch\",porttype=\"E_PORT\"})",
       "legendFormat": "{{switch}}.{{slot}}.{{port}}"
      }
     ]
    }
   ]
  }
 ]
}