{
 "title": "Brocade: Port Status (Realtime) - Prometheus",
 "tags": [
  "Brocade",
  "Realtime",
  "Prometheus"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   {
    "name": "Fabric",
    "query": {
     "query": "label_values(fosports_rx_power{}, fabric)"
    }
   },
   {
    "name": "Switch",
    "query": {
     "query": "label_values(fosports_rx_power{fabric=~\"$Fabric\"}, switch)"
    }
   },
   {
    "name": "Porttype",
    "query": {
     "query": "label_values(fosports_rx_power{fabric=~\"$Fabric\",switch=~\"$Switch\"}, porttype)"
    }
   },
   {
    "name": "Slot",
    "query": {
     "query": "label_values(fosports_rx_power{fabric=~\"$Fabric\",switch=~\"$Switch\",porttype=~\"$Porttype\"}, slot)"
    }
   },
   {
    "name": "Port",
    "query": {
     "query": "label_values(fosports_rx_power{fabric=~\"$Fabric\",switch=~\"$Switch\", porttype=~\"$Porttype\", slot=~\"$Slot\"}, port)"
    }
   },
   {
    "name": "errorcounter",
    "query": "Physical coding sublayer errors : pcs, Encoding OUT errors : enc_out, CRC errors : crc_errors, Invalid ordered set : inv_os, Link failures : link_failures, Link reset IN : lr_in, Link reset OUT : lr_out, Loss of sync : loss_of_sync, Loss of signal : loss_of_signal, C3 discards : class_3_discards, C3 RXTO discards : c3_rxto, C3 TXTO discards : c3_txto"
   }
  ]
 },
 "panels": [
  {
   "title": "Performance Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Aggregated throughput for all selected ports ",
   "type": "graph",
   "gridPos": { "h": 8, "w": 20, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum (rate(fosports_in_octets{fabric=~\"$Fabric\",switch=~\"$Switch\",porttype=~\"$Porttype\",slot=~\"$Slot\",port=~\"$Port\"}))",
     "legendFormat": "Aggregated RX Throughput"
    },
    {
     "expr": "sum (rate(fosports_out_octets{fabric=~\"$Fabric\",switch=~\"$Switch\",porttype=~\"$Porttype\",slot=~\"$Slot\",port=~\"$Port\"}))",
     "legendFormat": "Aggregated TX Throughput"
    }
   ]
  },
  {
   "title": "Aggregated RX/TX Ratio all selected ports ",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum (rate(fosports_in_octets{fabric=~\"$Fabric\",switch=~\"$Switch\",porttype=~\"$Porttype\",slot=~\"$Slot\",port=~\"$Port\"}))",
     "legendFormat": "Aggregated RX Throughput"
    },
    {
     "expr": "sum (rate(fosports_out_octets{fabric=~\"$Fabric\",switch=~\"$Switch\",porttype=~\"$Porttype\",slot=~\"$Slot\",port=~\"$Port\"}))",
     "legendFormat": "Aggregated TX Throughput"
    }
   ]
  },
  {
   "title": "Port RX throughput for all selected ports ",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(fosports_in_octets{fabric=~\"$Fabric\",switch=~\"$Switch\",porttype=~\"$Porttype\",slot=~\"$Slot\",port=~\"$Port\"})",
     "legendFormat": "{{switch}}.{{slot}}.{{port}}"
    }
   ]
  },
  {
   "title": "Port TX throughput for all selected ports ",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(fosports_in_octets{fabric=~\"$Fabric\",switch=~\"$Switch\",porttype=~\"$Porttype\",slot=~\"$Slot\",port=~\"$Port\"})",
     "legendFormat": "{{switch}}.{{slot}}.{{port}}"
    }
   ]
  },
  {
   "title": "Error Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "targets": [
    {}
   ]
  },
  {
   "title": "$errorcounter",
   "type": "table",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 20 },
   "repeat": "errorcounter",
   "targets": [
    {
     "expr": "rate(fosports_$errorcounter{fabric=~\"$Fabric\",switch=~\"$Switch\",porttype=~\"$Porttype\",slot=~\"$Slot\",port=~\"$Port\"})",
     "legendFormat": "{{switch}}.{{slot}}.{{port}}"
    }
   ]
  },
  {
   "title": "Error Details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 47 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "$errorcounter",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 48 },
     "repeat": "errorcounter",
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(fosports_$errorcounter{fabric=~\"$Fabric\",switch=~\"$Switch\",porttype=~\"$Porttype\",slot=~\"$Slot\",port=~\"$Port\"})",
       "legendFormat": "{{switch}}.{{slot}}.{{port}}"
      }
     ]
    }
   ]
  },
  {
   "title": "SFP Details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 48 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "SPF RX power in dBm",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 49 },
     "fieldConfig": { "defaults": { "unit": "dBm" } },
     "targets": [
      {
       "expr": "fosports_rx_power_dbm{fabric=~\"$Fabric\",switch=~\"$Switch\",porttype=~\"$Porttype\",slot=~\"$Slot\",port=~\"$Port\"}",
       "legendFormat": "{{switch}}.{{slot}}.{{port}}"
      }
     ]
    },
    {
     "title": "SPF TX power in dBm",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 49 },
     "fieldConfig": { "defaults": { "unit": "dBm" } },
     "targets": [
      {
       "expr": "fosports_tx_power_dbm{fabric=~\"$Fabric\",switch=~\"$Switch\",porttype=~\"$Porttype\",slot=~\"$Slot\",port=~\"$Port\"}",
       "legendFormat": "{{switch}}.{{slot}}.{{port}}"
      }
     ]
    },
    {
     "title": "SPF RX power in milliwatt",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 57 },
     "fieldConfig": { "defaults": { "unit": "mwatt" } },
     "targets": [
      {
       "expr": "fosports_rx_power{fabric=~\"$Fabric\",switch=~\"$Switch\",porttype=~\"$Porttype\",slot=~\"$Slot\",port=~\"$Port\"}",
       "legendFormat": "{{switch}}.{{slot}}.{{port}}"
      }
     ]
    },
    {
     "title": "SPF TX power in milliwatt",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 57 },
     "fieldConfig": { "defaults": { "unit": "mwatt" } },
     "targets": [
      {
       "expr": "fosports_tx_power{fabric=~\"$Fabric\",switch=~\"$Switch\",porttype=~\"$Porttype\",slot=~\"$Slot\",port=~\"$Port\"}",
       "legendFormat": "{{switch}}.{{slot}}.{{port}}"
      }
     ]
    }
   ]
  }
 ]
}