{
 "title": "Brocade: Initiator / Target Details (Realtime) - Prometheus",
 "tags": [
  "Brocade",
  "Realtime",
  "Prometheus"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Fabric",
    "query": {
     "query": "label_values(fosinittarget_in_octets{}, fabric)"
    }
   },
   {
    "name": "Type",
    "query": {
     "query": "label_values(fosinittarget_in_octets{fabric=~\"$Fabric\"}, devicetype)"
    }
   },
   {
    "name": "Device",
    "query": {
     "query": "label_values(fosinittarget_in_octets{fabric=~\"$Fabric\",devicetype=~\"$Type\"}, alias)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Performance Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Stacked RX Throughput",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(fosinittarget_in_octets{fabric=~\"$Fabric\",devicetype=~\"$Type\",alias=~\"$Device\"})",
     "legendFormat": "{{fabric}} - {{alias}}"
    }
   ]
  },
  {
   "title": "Stacked TX Throughput",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(fosinittarget_out_octets{fabric=~\"$Fabric\",devicetype=~\"$Type\",alias=~\"$Device\"})",
     "legendFormat": "{{fabric}} - {{alias}}"
    }
   ]
  },
  {
   "title": "RX Throughput Details",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(fosinittarget_in_octets{fabric=~\"$Fabric\",devicetype=~\"$Type\",alias=~\"$Device\"})",
     "legendFormat": "{{fabric}} - {{alias}}"
    }
   ]
  },
  {
   "title": "TX Throughput Details",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "rate(fosinittarget_out_octets{fabric=~\"$Fabric\",devicetype=~\"$Type\",alias=~\"$Device\"})",
     "legendFormat": "{{fabric}} - {{alias}}"
    }
   ]
  },
  { "title": "Performance Details $Device", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 }, "repeat": "Device" },
  {
   "title": "RX / TX Throughput  - $Device",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(fosinittarget_in_octets{fabric=~\"$Fabric\",devicetype=~\"$Type\",alias=~\"$Device\"})",
     "legendFormat": "{{alias}} RX"
    },
    {
     "expr": "rate(fosinittarget_out_octets{fabric=~\"$Fabric\",devicetype=~\"$Type\",alias=~\"$Device\"})",
     "legendFormat": "{{alias}} TX"
    }
   ]
  },
  {
   "title": "RX / TX Throughput",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 3, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(fosinittarget_in_octets{fabric=~\"$Fabric\",devicetype=~\"$Type\",alias=~\"$Device\"})",
     "legendFormat": "RX"
    },
    {
     "expr": "rate(fosinittarget_out_octets{fabric=~\"$Fabric\",devicetype=~\"$Type\",alias=~\"$Device\"})",
     "legendFormat": "TX"
    }
   ]
  },
  {
   "title": "RX / TX Throughput % - $Device",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 * rate(fosinittarget_in_octets{fabric=~\"$Fabric\",devicetype=~\"$Type\",alias=~\"$Device\"}) / (rate(fosinittarget_in_octets{fabric=~\"$Fabric\",devicetype=~\"$Type\",alias=~\"$Device\"}) +rate(fosinittarget_out_octets{fabric=~\"$Fabric\",devicetype=~\"$Type\",alias=~\"$Device\"}))",
     "legendFormat": "RX"
    },
    {
     "expr": "100 * rate(fosinittarget_out_octets{fabric=~\"$Fabric\",devicetype=~\"$Type\",alias=~\"$Device\"}) / (rate(fosinittarget_in_octets{fabric=~\"$Fabric\",devicetype=~\"$Type\",alias=~\"$Device\"}) +rate(fosinittarget_out_octets{fabric=~\"$Fabric\",devicetype=~\"$Type\",alias=~\"$Device\"}))",
     "legendFormat": "TX"
    }
   ]
  },
  {
   "title": "Physical Errors",
   "type": "table",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "fosinittarget_address_errors{fabric=~\"$Fabric\",devicetype=~\"$Type\",alias=~\"$Device\"}",
     "legendFormat": "address errors"
    },
    {
     "expr": "fosinittarget_bad_eofs_received{fabric=~\"$Fabric\",devicetype=~\"$Type\",alias=~\"$Device\"}",
     "legendFormat": "bad eofs received"
    },
    {
     "expr": "fosinittarget_crc_errors{fabric=~\"$Fabric\",devicetype=~\"$Type\",alias=~\"$Device\"}",
     "legendFormat": "crc errors"
    },
    {
     "expr": "fosinittarget_delimiter_errors{fabric=~\"$Fabric\",devicetype=~\"$Type\",alias=~\"$Device\"}",
     "legendFormat": "delimiter errors"
    },
    {
     "expr": "fosinittarget_enc_out{fabric=~\"$Fabric\",devicetype=~\"$Type\",alias=~\"$Device\"}",
     "legendFormat": "encoding out"
    },
    {
     "expr": "fosinittarget_in_crc_errors{fabric=~\"$Fabric\",devicetype=~\"$Type\",alias=~\"$Device\"}",
     "legendFormat": "in crc errors"
    },
    {
     "expr": "fosinittarget_itw{fabric=~\"$Fabric\",devicetype=~\"$Type\",alias=~\"$Device\"}",
     "legendFormat": "invalid transimission word"
    },
    {
     "expr": "fosinittarget_pcs{fabric=~\"$Fabric\",devicetype=~\"$Type\",alias=~\"$Device\"}",
     "legendFormat": "physical coding sublayer"
    }
   ]
  },
  {
   "title": "Link Errors",
   "type": "table",
   "gridPos": { "h": 11, "w": 8, "x": 8, "y": 26 },
   "targets": [
    {
     "expr": "fosinittarget_link_failures{fabric=~\"$Fabric\",devicetype=~\"$Type\",alias=~\"$Device\"}",
     "legendFormat": "link failures"
    },
    {
     "expr": "fosinittarget_loss_of_signal{fabric=~\"$Fabric\",devicetype=~\"$Type\",alias=~\"$Device\"}",
     "legendFormat": "loss of signal"
    },
    {
     "expr": "fosinittarget_loss_of_sync{fabric=~\"$Fabric\",devicetype=~\"$Type\",alias=~\"$Device\"}",
     "legendFormat": "loss of sync"
    },
    {
     "expr": "fosinittarget_lr_in{fabric=~\"$Fabric\",devicetype=~\"$Type\",alias=~\"$Device\"}",
     "legendFormat": "lr in"
    },
    {
     "expr": "fosinittarget_lr_out{fabric=~\"$Fabric\",devicetype=~\"$Type\",alias=~\"$Device\"}",
     "legendFormat": "lr out"
    }
   ]
  },
  {
   "title": "Discard Errors",
   "type": "table",
   "gridPos": { "h": 11, "w": 8, "x": 16, "y": 26 },
   "targets": [
    {
     "expr": "fosinittarget_c3_rxto{fabric=~\"$Fabric\",devicetype=~\"$Type\",alias=~\"$Device\"}",
     "legendFormat": "c3 rx timeout"
    },
    {
     "expr": "fosinittarget_c3_txto{fabric=~\"$Fabric\",devicetype=~\"$Type\",alias=~\"$Device\"}",
     "legendFormat": "c3 tx timeout"
    },
    {
     "expr": "fosinittarget_class_3_discards{fabric=~\"$Fabric\",devicetype=~\"$Type\",alias=~\"$Device\"}",
     "legendFormat": "class 3 discards"
    }
   ]
  },
  {
   "title": "SFP RX Power of $Device",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "dBm" } },
   "targets": [
    {
     "expr": "fosinittarget_rx_power_dbm{fabric=~\"$Fabric\",devicetype=~\"$Type\",alias=~\"$Device\"}",
     "legendFormat": "{{fabric}} - {{alias}}"
    }
   ]
  },
  {
   "title": "SFP TX Power of $Device",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "dBm" } },
   "targets": [
    {
     "expr": "fosinittarget_rx_power_dbm{fabric=~\"$Fabric\",devicetype=~\"$Type\",alias=~\"$Device\"}",
     "legendFormat": "{{fabric}} - {{alias}}"
    }
   ]
  }
 ]
}